# -*- coding: utf-8 -*-
"""Task_02_DS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wShnrNSP4tYpWI-HOUr-lhFjohO0k9Pi

## import **library** **bold text**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# **Read Dataset by Pandas library**

> Add blockquote


"""

df=pd.read_csv('tested.csv')

df.head(20)

"""## **To Get number of row and column**"""

df.shape

"""# **ACCESS The feature in our Dataset**"""

df.columns

df.describe()

"""# **Check if there are any empthy Value**"""

df.isnull().sum()

"""# fill missing Value in Each **Column**"""

mean_value_Age=df['Age'].mean()
mean_Value_Fare=df['Fare'].mean()

df['Age'].fillna(mean_value_Age,inplace=True)
df['Fare'].fillna(mean_Value_Fare,inplace=True)

"""# **Drop the column which has the most missing** **Value**"""

df.drop(columns=['Cabin'],inplace=True)

"""# **Check After cleaning Data **"""

df.isnull().sum()

"""# **Data Visualization **"""

sns.countplot(x='Sex', hue='Survived', data=df)
plt.title('Survival Counts by Sex')
plt.xlabel('Sex')
plt.ylabel('Count')
plt.legend(title='Survived', labels=['No', 'Yes'])
plt.show()

"""# **# Calculate survival** **rates**"""

survival_rate = df.groupby('Sex')['Survived'].mean()
survival_rate

sns.catplot(x='Pclass', hue='Survived', col='Sex', data=df, kind='count', height=4, aspect=0.7)
plt.subplots_adjust(top=0.8)
plt.suptitle('Survival Counts by Pclass and Sex')
plt.xlabel('Passenger Class')
plt.ylabel('Count')
plt.show()