# -*- coding: utf-8 -*-
"""Task-01 DS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ujtV6o45jmLUjuSYcEH663RCKlSo43Y

import ***libraries***
"""

import pandas as pd
import matplotlib.pyplot as plt

"""**Reading dataset**"""

df=pd.read_csv('world_population.csv')

df.head()

df.describe()

"""**EDA Explorartory data analysis**"""

df.shape

df.dtypes

df.info()

"""**check for missing value**"""

df.isnull().sum()

df.nunique()

"""**check 10 countries with the most population **"""

top_10_countries = df.groupby('Country/Territory')['2022 Population'].sum().sort_values(ascending=False).head(10)
print(top_10_countries)

"""**Data visualization**"""

top_most_population = df.groupby(by='Country/Territory')['2022 Population'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(12, 6))
plt.bar(top_most_population.index, top_most_population.values, color='skyblue')
plt.xlabel("Countries", fontsize=12)
plt.ylabel("Population", fontsize=12)
plt.title("Top 10 Countries with the most population", fontsize=14)
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.tight_layout()
plt.show()